### ISSUE TITLE
Sample apps won't run due to config exception

### ISSUE THREAD

**Issue by BadLambdaJamma** [Sustainsys/Saml2#1012]
I pull the latest sources, compile and run the SampleOwinApplication.

I am getting this error:
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.'

   at Sustainsys.Saml2.Configuration.IdentityConfiguration..ctor(Boolean loadConfig)
   at Sustainsys.Saml2.Configuration.SPOptions..ctor() in C:\workspace\Saml2\Sustainsys.Saml2\Configuration\SPOptions.cs:line 25
   at SampleOwinApplication.Startup.CreateSPOptions() in C:\workspace\Saml2\Samples\SampleOwinApplication\App_Start\Startup.Auth.cs:line 89
   at SampleOwinApplication.Startup.CreateSaml2Options() in C:\workspace\Saml2\Samples\SampleOwinApplication\App_Start\Startup.Auth.cs:line 52
   at SampleOwinApplication.Startup.ConfigureAuth(IAppBuilder app) in C:\workspace\Saml2\Samples\SampleOwinApplication\App_Start\Startup.Auth.cs:line 47
   at SampleOwinApplication.Startup.Configuration(IAppBuilder app) in C:\workspace\Saml2\Samples\SampleOwinApplication\Startup.cs:line 11

The project SustainSys.Saml2 already includes the reference so I am not sure Why the assembly is failing to load: (Dependencies=>NuGet=>System.Configuration.ConfigurationManager(4.4.1)

What Do I need to do to make this sample run?

Thanks
-Jonathan

**Comment by AndersAbel** [comment]
This is something that needs to be looked into. I have not validated the sample applications after the merge of the .NET Core port, so it might be that something is wrong in the current source tree.

**Comment by RobinLjungqvist** [comment]
I can also verify that the problem in SampleOwinApplication the problem also exists in the SampleMvcApplication.

**Comment by BadLambdaJamma** [comment]
I pulled fresh sources (including commits from 9828b8b) and I still had the same issue.  This appears to be a known issue when a .NET4x  assembly references a .NET standard assembly and the referenced types exist in different assemblies (System.Configuration versus System.Configuration.ConfigurationManager).

As a workaround I nuget installed ConfigurationManager version 4.4.0 for the SampleOwinApplication project and the Owin sample is now functional:   You must specify the explicit version that the Standard class library is using:

**Install-Package System.Configuration.ConfigurationManager -Version 4.4.0**

**Comment by AndersAbel** [comment]
@BadLambdaJamma thanks for finding that. One option might be to multi-target the base library. Will check into this within next few days.
