### ISSUE TITLE
Object reference exception at Sustainsys.Saml2.Saml2P.Saml2Response.ValidateSignature(IOptions options)

### ISSUE THREAD

**Issue by bsunilkumar** [Sustainsys/Saml2#1046]
We are upgraded our solutions to .NetFramework 4.7.2 and DotnetCore 2.1 iam getting the below object reference exception with SAML

We using the SAML2 version 0.23.0.0
Sustainsys.Saml2.Saml2P.Saml2Response, Sustainsys.Saml2, Version=0.23.0.0, Culture=neutral, PublicKeyToken=null

Object reference not set to an instance of an object.
   at Sustainsys.Saml2.Saml2P.Saml2Response.ValidateSignature(IOptions options)
   at Sustainsys.Saml2.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sustainsys.Saml2.Saml2P.Saml2Response.GetClaims(IOptions options)

SAML Response:

<saml2p:Response 
    Destination="http://test.localhost:5000/Saml/Acs" 
    ID="id1795ceab9f394340bb25600fccd06bd3" 
    Version="2.0" 
    IssueInstant="2018-12-17T11:26:38Z" 
    xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml2:Issuer 
        xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">http://stubidp.sustainsys.com/Metadata
    </saml2:Issuer>
    <Signature 
        xmlns="http://www.w3.org/2000/09/xmldsig#">
        <SignedInfo>
            <CanonicalizationMethod 
                Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            <SignatureMethod 
                Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
            <Reference 
                URI="#id1795ceab9f394340bb25600fccd06bd3">
                <Transforms>
                    <Transform 
                        Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <Transform 
                        Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                </Transforms>
                <DigestMethod 
                    Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                <DigestValue>
                    tayCxJOmqWnnTlSsVFstsESRdqdCTjGh5aqLGecUB7s=
                </DigestValue>
            </Reference>
        </SignedInfo>
        <SignatureValue>iOlIFvkqFvuu3aGre9SvT90a4NMzGqdLeHgL5P4slpIjQDupfMwPGqnVwXjK36AIy5o2v/YnoJjgVLYppUbZneY4it10Hm+RSkBbRJsA+RqlrGs4JyS7FEScdORV/
            t4fbGp8Y3DNGch27WqB4LnH2cBLEOx9DNz3PRJFXAZgWvs=
        </SignatureValue>
        <KeyInfo>
            <X509Data>
                <X509Certificate>MIICFTCCAYKgAwIBAgIQzfcJCkM1YahDtRGYsLphrDAJBgUrDgMCHQUAMCExHzAdBgNVBAMTFnN0dWJpZHAuc3VzdGFpbnN5cy5jb20wHhcNMTcxMjE0MTE1NDUwWhcNMzkxMjMxMjM1OTU5WjAhMR8wHQYDVQQDExZzdHViaWRwLnN1c3RhaW5zeXMuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDSSq8EX46J1yprfaBdh4pWII+/E7ypHM1NjG7mCwFwbkjq2tpSBuoASrQftbjIKqjVzxtxETw802VJu5CJR4d3Zdy5jD8NRTesfaQDazX7iiqisfnxmIdDhtJS0lXeBlj4MipoUW6l8Qsjx7ltZSwdfFLyh+bMqIrwOhMWGs82vQIDAQABo1YwVDBSBgNVHQEESzBJgBCBBNba7KNF5wnXqmYcejn6oSMwITEfMB0GA1UEAxMWc3R1YmlkcC5zdXN0YWluc3lzLmNvbYIQzfcJCkM1YahDtRGYsLphrDAJBgUrDgMCHQUAA4GBAHonBGahlldp7kcN5HGGnvogT8a0nNpM7GMdKhtzpLO3Uk3HyT3AAIKWiSoEv2n1BTalJ/CY/+te/JZPVGhWVzoi5JYytpj5gM0O7RH0a3/yUE8S8YLV2h0a2gsdoMvTRTnTm9CnXezCKqhjYjwsmOZtiCIYuFqX71d/pg5uoJfs</X509Certificate>
            </X509Data>
        </KeyInfo>
    </Signature>
    <saml2p:Status>
        <saml2p:StatusCode 
            Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </saml2p:Status>
    <saml2:Assertion 
        xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" 
        Version="2.0" 
        ID="_56e9a121-c7b2-4afb-af7b-0807578b8d41" 
        IssueInstant="2018-12-17T11:26:38Z">
        <saml2:Issuer>http://stubidp.sustainsys.com/Metadata</saml2:Issuer>
        <saml2:Subject>
            <saml2:NameID 
                Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">kodos
            </saml2:NameID>
            <saml2:SubjectConfirmation 
                Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml2:SubjectConfirmationData 
                    NotOnOrAfter="2018-12-17T11:28:38Z" 
                    Recipient="http://test.localhost:5000/Saml/Acs" />
            </saml2:SubjectConfirmation>
        </saml2:Subject>
        <saml2:Conditions 
            NotOnOrAfter="2018-12-17T11:28:38Z" />
        <saml2:AuthnStatement 
            AuthnInstant="2018-12-17T11:26:38Z" 
            SessionIndex="42">
            <saml2:AuthnContext>
                <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml2:AuthnContextClassRef>
            </saml2:AuthnContext>
        </saml2:AuthnStatement>
    </saml2:Assertion>
</saml2p:Response>

Sammple Code:

private const string _SamlNameIdentifierTypeNs = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier";

        private Lazy<AuthServicesOptions> _Options;
        public AuthServicesOptions Options => _Options.Value;
        private SPOptions SpOptions { get; set; }
		
		
		
		 Saml2Binding binding = Options.Notifications.GetBinding(httpRequestData);
            validationResults = new List<ValidationResult>();

            if (binding == null)
            {
                validationResults = ValidationResultFactory.NewValidationResultAsList("Could not get saml binding for Http Request Data", nameof(httpRequestData));
                return null;
            }

            string username = null;

            try
            {
                UnbindResult unbindResult = binding.Unbind(httpRequestData, null);
                Options.Notifications.MessageUnbound(unbindResult);
                
                Saml2Response samlResponse = new Saml2Response(unbindResult.Data, httpRequestData.StoredRequestState?.MessageId);
                // Get Claims can only be called once, with the same options. Otherwise it will throw an error.
                ClaimsPrincipal principal = new ClaimsPrincipal(samlResponse.GetClaims(Options));
                Options.SPOptions.SystemIdentityModelIdentityConfiguration.ClaimsAuthenticationManager.Authenticate(null, principal);

                username = principal.Claims.SingleOrDefault(c => c.Type == _SamlNameIdentifierTypeNs)?.Value;

                if (principal.Claims.SingleOrDefault(c => c.Type == _SamlNameIdentifierTypeNs)?.Value == null)
                    validationResults = ValidationResultFactory.NewValidationResultAsList("Could not find Identifier in SAML", nameof(httpRequestData));
            }
            catch (FormatException)
            {
                validationResults = ValidationResultFactory.NewValidationResultAsList("The SAML Response did not contain valid BASE64 encoded data.", nameof(httpRequestData));
            }
            catch (XmlException)
            {
                // Difficult to unit test this as we can't sign an invalid xml...
                validationResults = ValidationResultFactory.NewValidationResultAsList("The SAML response contains incorrect XML.", nameof(httpRequestData));
            }
            catch (Exception ex)
            {
                // TODO: Once we have properly error logging implemented, we should log this exception.
                //validationResults = ValidationResultFactory.NewValidationResultAsList(ex.Message, nameof(httpRequestData));
                //Log to console for debugging
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
                validationResults = ValidationResultFactory.NewValidationResultAsList("There was an unexpected error logging in via SAML", nameof(httpRequestData));
                Console.WriteLine("*** UNHANDLED EXCEPTION OCCURRED ***");
                Console.WriteLine(ex.ToString());
            }

Thanks,
Sunil Kumar B

**Comment by bsunilkumar** [comment]
[SAML Response.txt](https://github.com/Sustainsys/Saml2/files/2690415/SAML.Response.txt)

**Comment by bsunilkumar** [comment]
SpOptions.Logger is throwing null exception

Assigned logger object to spoptions as below resolved the null exception.
 spOptions.Logger = new SamlLogger();

SamlLogger.cs
public class SamlLogger : ILoggerAdapter
    {
}
