### ISSUE TITLE
Encoding error using Artifact Binding against ADFS3.0

### ISSUE THREAD

**Issue by drake2k** [Sustainsys/Saml2#1120]
Hi,

When using artifact binding with ADFS 3.0 I get the following error:

```
The remote server returned an error: (415) Cannot process the message because the content type 'application/octet-stream' was not the expected type 'text/xml; charset=utf-8'..
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at System.Net.WebClient.UploadString(Uri address, String data)
   at Sustainsys.Saml2.Saml2P.Saml2SoapBinding.SendSoapRequest(String payload, Uri destination, IEnumerable`1 clientCertificates)
   at Sustainsys.Saml2.WebSso.Saml2ArtifactBinding.ResolveArtifact(String artifact, StoredRequestState storedRequestState, IOptions options)
   at Sustainsys.Saml2.WebSso.Saml2ArtifactBinding.Unbind(HttpRequestData request, IOptions options)
   at Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Sustainsys.Saml2.Owin.Saml2AuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
```

Could this somehow be related to #1078 ?

### Information needed
1. What nuget packages are you using
Sustainsys.Saml2.Owin v2.3.0
2. What is the expected behaviour
Authentication works
3. What happens instead.
Error Message

### Additional info
Compiled against .net4.7
Runtime is .net4.8

**Comment by AndersAbel** [comment]
I'm adding a fix for this, but haven't been able to test it with a real Idp. If problem persists after 2.5 release, please comment and I'll re-open.
