### ISSUE TITLE
Not working with IOS 12 devices

### ISSUE THREAD

**Issue by wkrosner** [Sustainsys/Saml2#1216]
Hello, the library is not working with ios 12 devices.  I have no idea why.  I am willing to pay for support for this issue.  We get a Exception information: 

    Exception type: UnexpectedInResponseToException 
    Exception message: Received message s2e7f4d05f4fe238ff859caf4131ad0678f3033f5c contains unexpected InResponseTo "id4e4a769f4ae646a19a6f7ec4fa099eea". No cookie preserving state from the request was found so the message was not expected to have an InResponseTo attribute. This error typically occurs if the cookie set when doing SP-initiated sign on have been lost.
   at Sustainsys.Saml2.Saml2P.Saml2Response.ValidateInResponseTo(IOptions options, IEnumerable`1 claimsIdentities)
   at Sustainsys.Saml2.Saml2P.Saml2Response.GetClaims(IOptions options, IDictionary`2 relayData)
   at Sustainsys.Saml2.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState, IdentityProvider identityProvider, String relayState)
   at Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Sustainsys.Saml2.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by wkrosner** [comment]
This issue resolved after reboot.
