### ISSUE TITLE
Saml2Hander AuthenticateAsync Is Not implemented

### ISSUE THREAD

**Issue by Ringx86** [Sustainsys/Saml2#1301]
### Information needed
1. What nuget packages are you using
2.8.0
2. What is the expected behaviour

3. What happens instead. In the case of an exception, this includes the exception typ, complete exception message (personal information may be redacted) and a stack trace.
trace:
System.NotImplementedException: The method or operation is not implemented.
   at Sustainsys.Saml2.AspNetCore2.Saml2Handler.AuthenticateAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
...

### Additional info
NetCore 3.1

My Demo Code:
```c#
authenticationBuilder.AddSaml2("saml",options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.SignOutScheme = IdentityServerConstants.DefaultCookieAuthenticationScheme;
                options.SPOptions.EntityId = new EntityId("https://localhost:44369/Saml2");
                options.IdentityProviders.Add(
                    new IdentityProvider(
                        new EntityId("http://localhost:52071/Metadata"), options.SPOptions)
                    {
                        LoadMetadata = true
                    });

                options.SPOptions.ServiceCertificates.Add(new X509Certificate2("Sustainsys.Saml2.Tests.pfx"));
            });

```

**Comment by AndersAbel** [comment]
An external authentication handler like Saml2 does not support the `AuthenticateAsync` call. It supports challenge to initialize the login and then the result is stored in the external cookie scheme - call AuthenticateAsync on that scheme to get the result.
