### ISSUE TITLE
Response Assertion Containing non-ASCII characters throws InvalidSignatureException

### ISSUE THREAD

**Issue by mwhouser** [Sustainsys/Saml2#1311]
## Problem

We are using Azure AD as our IdP. A user's last name is "Castañeda" and the assertion is including the following:

```xml
<Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname">
  <AttributeValue>Castañeda Ortiz</AttributeValue>
</Attribute>
```

When I call `Saml2Response.GetClaims`, an exception of type `InvalidSignatureException` is thrown.

> Signature didn't verify. Have the contents been tampered with?

```
   at Sustainsys.Saml2.XmlHelpers.VerifySignature(IEnumerable`1 signingKeys, SignedXml signedXml, XmlElement signatureElement, Boolean validateCertificate)
   at Sustainsys.Saml2.XmlHelpers.IsSignedByAny(XmlElement xmlElement, IEnumerable`1 signingKeys, Boolean validateCertificate, String minimumSigningAlgorithm)
   at Sustainsys.Saml2.Saml2P.Saml2Response.<>c__DisplayClass60_0.<ValidateSignature>b__0(XmlElement a)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Sustainsys.Saml2.Saml2P.Saml2Response.ValidateSignature(IOptions options, IdentityProvider idp)
   at Sustainsys.Saml2.Saml2P.Saml2Response.<CreateClaims>d__66.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sustainsys.Saml2.Saml2P.Saml2Response.GetClaims(IOptions options, IDictionary`2 relayData)
   at Sustainsys.Saml2.Saml2P.Saml2Response.GetClaims(IOptions options)
```

## What Should Happen

Calling `Saml2Response.GetClaims` should succeed.

## Workaround

Removing the offending `ñ` from the user's name avoids the issue.

## Additional Notes

* I have confirmed that the string passed to `Saml2Response.Read` has the correct `ñ` character.

## Environment

Nuget Package: Sustainsys.Saml2 version 2.8.0
Framework Version: .NET Framework 4.7.2
Framework Installed: .NET Framework 4.7.2
MVC Version: 5.2.7

**Comment by AlexAlexGoTO** [comment]
How actually I can get that assertion from response ? 
this is my /acs url...
```
[Route("api/Acs")]
[HttpPost]
public async Task<IHttpActionResult> SamlSignInAsync()
```

**Comment by AndersAbel** [comment]
Thanks for a good bug report and validation. Did you do any debugging of the library to understand why it fails? Looks like it is some kind of encoding issue.

**Comment by mwhouser** [comment]
No, I didn't get into the library. I stumbled upon it when:

(a) It worked fine for me, but not for my customer
(b) Found a forum post about SAML and encodings
(c) Confirmed the customer's SAML responses contained an offending character
(d) Tested for myself using Azure AD as the IdP, forcing an offending character

What I'm not able to confirm is whether (due to the encoding) Azure AD is signing the SAML response properly or not.
