### ISSUE TITLE
"Empty reference for Xml signature is not allowed" after a metadata upgrade

### ISSUE THREAD

**Issue by spaasis** [Sustainsys/Saml2#1470]
Hi, and thanks for this brilliant tool!

After a service provider updated their SAML2 metadata from https://virtu-ds.csc.fi/fed/virtu/virtu-metadata-v8.xml to https://virtu-ds.csc.fi/fed/virtu/virtu-metadata-v9.xml trying to load the metadata fails with:

```
2024-09-24 15:47:11.844 +03:00 [ERR] Metadata loading failed from https://virtu-ds.csc.fi/fed/virtu/virtu-metadata-v9.xml
Sustainsys.Saml2.Exceptions.InvalidSignatureException: Empty reference for Xml signature is not allowed.
   at Sustainsys.Saml2.XmlHelpers.ValidateReference(SignedXml signedXml, XmlElement xmlElement, String mininumDigestAlgorithm)
   at Sustainsys.Saml2.XmlHelpers.ValidateSignedInfo(SignedXml signedXml, XmlElement xmlElement, String minIncomingSignatureAlgorithm)
   at Sustainsys.Saml2.XmlHelpers.IsSignedByAny(XmlElement xmlElement, IEnumerable`1 signingKeys, Boolean validateCertificate, String minimumSigningAlgorithm)
   at Sustainsys.Saml2.Metadata.MetadataLoader.ValidateSignature(XmlDictionaryReader reader, IEnumerable`1 signingKeys, Boolean validateCertificate, String minIncomingSigningAlgorithm)
   at Sustainsys.Saml2.Metadata.MetadataLoader.Load(String metadataLocation, IEnumerable`1 signingKeys, Boolean validateCertificate, String minIncomingSigningAlgorithm)
   at Sustainsys.Saml2.Metadata.MetadataLoader.LoadFederation(String metadataLocation, IEnumerable`1 signingKeys, Boolean validateCertificate, String minIncomingSigningAlgorithm)
   at Sustainsys.Saml2.Federation.LoadMetadata()
```

I guess the error is due to this difference:
In the old version
```
<EntityDescriptor xmlns:ds=[http://www.w3.org/2000/09/xmldsig#](http://www.w3.org/2000/09/xmldsig) entityID=http://idp.valtion.fi/adfs/services/trust>
    <IDPSSODescriptor WantAuthnRequestsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ds=[http://www.w3.org/2000/09/xmldsig#](http://www.w3.org/2000/09/xmldsig)>
      <KeyDescriptor xmlns:ds=[http://www.w3.org/2000/09/xmldsig#](http://www.w3.org/2000/09/xmldsig)>
        <ds:KeyInfo xmlns:ds=[http://www.w3.org/2000/09/xmldsig#](http://www.w3.org/2000/09/xmldsig)>
```

And the new one
```
<EntityDescriptor xmlns:ds=[http://www.w3.org/2000/09/xmldsig#](http://www.w3.org/2000/09/xmldsig) entityID=http://idp.valtion.fi/adfs/services/trust>
    <IDPSSODescriptor WantAuthnRequestsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
      <KeyDescriptor>
        <ds:KeyInfo>
```

As far as I know, the new version is still valid SAML2 XML?

I'm using **Sustainsys.Saml2.AspNetCore2** version **2.9.2**

**Comment by spaasis** [comment]
Ah, the error is actually in the missing URI description in the SignedInfo of the new metadata:
```<EntitiesDescriptor ID="virtu-20241003101503" Name="virtu" validUntil="2024-10-31T11:33:31Z" xsi:schemaLocation="urn:oasis:names:tc:SAML:2.0:metadata saml-schema-metadata-2.0.xsd http://www.w3.org/2000/09/xmldsig# xmldsig-core-schema.xsd">
<ds:Signature>
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
<ds:Reference URI="">
```
I'll see about this with the service provider.


For reference, the error is thrown from here:
```
        private static void ValidateReference(
            SignedXml signedXml,
            XmlElement xmlElement,
            string mininumDigestAlgorithm)
        {
            if (signedXml.SignedInfo.References.Count == 0)
            {
                throw new InvalidSignatureException("No reference found in Xml signature, it doesn't validate the Xml data.");
            }

            if (signedXml.SignedInfo.References.Count != 1)
            {
                throw new InvalidSignatureException("Multiple references for Xml signatures are not allowed.");
            }

            var reference = (Reference)signedXml.SignedInfo.References[0];
            if ( string.IsNullOrWhiteSpace( reference.Uri ) )
            {
                throw new InvalidSignatureException( "Empty reference for Xml signature is not allowed." );
            }
```

**Comment by spaasis** [comment]
Yup that was it. The service provider updated their metadata doc and it works again as expected

**Comment by AndersAbel** [comment]
Happy to see that you found out and fixed it. Using an empty reference is allowed in the general XML DSIG standard and should be treated as a reference to the root of the containing document. However, the SAML2 standard contains a more restrictive profile for XML signature handling which requires a value for the URI of the Reference.
