### ISSUE TITLE
configuring mulitple Azure Entra Id Saml2 based IdP's in in middleware, and attempting to invoke chosesn IdP in the Acs Challange, I get the following exception

### ISSUE THREAD

**Issue by joshuafranklinengineeringsystems** [Sustainsys/Saml2#1480]
My code works perfeclty fine if I enable one or the other IdP's but when I enabled them both at the same time I get the following internal execption:

System.Collections.Generic.KeyNotFoundException: No Idp with entity id "https://sts.windows.net/8c47ef63-1296-4e7a-97b7-649f4eb09330/" found.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'Sustainsys.Saml2.Metadata.EntityId' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sustainsys.Saml2.Configuration.IdentityProviderDictionary.get_Item(EntityId entityId)
   --- End of inner exception stack trace ---
   at Sustainsys.Saml2.Configuration.IdentityProviderDictionary.get_Item(EntityId entityId)
   at Sustainsys.Saml2.Configuration.Saml2Notifications.<>c.<.ctor>b__84_18(EntityId ei, IDictionary`2 rd, IOptions opt)
   at Sustainsys.Saml2.WebSso.AcsCommand.GetIdpContext(XmlElement xml, HttpRequestData request, IOptions options)
   at Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Sustainsys.Saml2.AspNetCore2.Saml2Handler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   
   Part of the middleware, that iterates over a look of 1 to n IdP's from appsetting.json.

**Comment by rikrak** [comment]
Could it be a case-sensitivity issue?  I think the Idp identifiers are case-sensitive
Can you share the relevant parts of your appsettings.json?

**Comment by joshuafranklinengineeringsystems** [comment]
I use and copy the strings as given on the Entra Id Saml Config. I may have been over zealous with my value.equal(n, OrdinalStringNautul) - or something like this. Alan TaylorDirector,  Software Engineer+44 7768 831597Joshua Franklin Engineering Systems LimitedRegistered Office: Flat 2 Grove Court, 9 Gumbrell Mews, REDHILL, RH1 1TGVAT Registration Number: 440 7683 87Registered Number: 14299506Registered in England & WalesOn 10 Jan 2025, at 09:47, Rik Crompton ***@***.***> wrote:﻿
Could it be a case-sensitivity issue?  I think the Idp identifiers are case-sensitive
Can you share the relevant parts of your appsettings.json?

**Comment by joshuafranklinengineeringsystems** [comment]
I will add the details.

**Comment by AndersAbel** [comment]
If you call `AddSaml2` multiple times each instance has to get its own `ModulePath`.

**Comment by joshuafranklinengineeringsystems** [comment]
> If you call `AddSaml2` multiple times each instance has to get its own `ModulePath`.

Ok. Thanks. I'll take a new look at th implementation and see where I'd need to made his adjustment to accommodate the use of unique ModulePath's. 

Thank you.
