### ISSUE TITLE
System.NullReferenceException inside ProcessAuthenticationStatement method

### ISSUE THREAD

**Issue by FVilevski** [Sustainsys/Saml2#776]
Hi, I am having some troubles with processing of response from IdP on the SP side. I am using OWIN implementation for SP and it throws System.NullReferenceException Object reference not set to an instance of an object when reading the response. Here is the StackTrace, if you need additional info, please let me know.

BTW: Both IdP and SP are tested against testshib.org successfully

`at Kentor.AuthServices.Saml2P.Saml2PSecurityTokenHandler.ProcessAuthenticationStatement(Saml2AuthenticationStatement statement, ClaimsIdentity subject, String issuer)
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ProcessStatement(Collection`1 statements, ClaimsIdentity subject, String issuer)
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.CreateClaims(Saml2SecurityToken samlToken)
   at Kentor.AuthServices.Saml2P.Saml2PSecurityTokenHandler.CreateClaims(Saml2SecurityToken samlToken)
   at Kentor.AuthServices.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options)
   at Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState)
   at Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()`

**Comment by jahmai** [comment]
Same, it only seems to happen if they enable assertion encryption.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Kentor.AuthServices.Saml2P.Saml2PSecurityTokenHandler.ProcessAuthenticationStatement(Saml2AuthenticationStatement statement, ClaimsIdentity subject, String issuer)
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ProcessStatement(Collection`1 statements, ClaimsIdentity subject, String issuer)
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.CreateClaims(Saml2SecurityToken samlToken)
   at Kentor.AuthServices.Saml2P.Saml2PSecurityTokenHandler.CreateClaims(Saml2SecurityToken samlToken)
   at Kentor.AuthServices.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options)
   at Intrinsic.Messaging.Protocols.Core.Sasl.Saml.Http.SamlAssertion.Validate(HttpRequestData requestData, StoredRequestState storedState, SamlServiceProviderMetadata serviceProviderMetadata, IEnumerable`1 identityProviderMetadatas) in R:\Agent0\work\cef3376167bc0d5d\Source\Libraries\Intrinsic.Messaging.Server\Messaging\Protocols\Core\Sasl\Saml\Http\SamlAssertion.cs:line 44
   at Intrinsic.Messaging.Protocols.Core.Sasl.Saml.Http.SamlController.<>c__DisplayClass17_0.<<PostAssertion>b__0>d.MoveNext() in R:\Agent0\work\cef3376167bc0d5d\Source\Libraries\Intrinsic.Messaging.Server\Messaging\Protocols\Core\Sasl\Saml\Http\SamlController.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Intrinsic.Messaging.Http.XController.<ExecuteAsync>d__45.MoveNext() in R:\Agent0\work\cef3376167bc0d5d\Source\Libraries\Intrinsic.Messaging.Server\Messaging\Http\XController.cs:line 291
```

**Comment by explunit** [comment]
@FVilevski and @jahmai: are you able to post the SAML that caused this error?

**Comment by jahmai** [comment]
I could, but how would you decrypt it?

**Comment by explunit** [comment]
😄  Yes, you're right

One hack to get to the underlying assertions is to handle the `AcsCommandResultCreated` notification and then use reflection to invoke the `retrieveAssertionElements` method on the Saml2Response.

**Comment by jahmai** [comment]
So this error is happening in our production system against a customer who has loaded that systems service provider metadata, so I can't attach a debugger or alter the code with a hack to grab that context and I can't get the customer to point their IdP to a development environment, so unfortunately that's not an option :(

They've disabled encryption and it's now working, really sorry that I can't offer more info, maybe @FVilevski can.

**Comment by explunit** [comment]
@jahmai Do you know if the response/assertion was encrypted, or also the NameId? I don't think this library supports encrypted NameId.

**Comment by jahmai** [comment]
NameID encryption may have been enabled initially yes, which we subsequently disabled all encryption and it started working. Good to know that Kentor doesn't support it, I'll make that a standard requirement to disable it at our customers.
