### ISSUE TITLE
Metadata not available for ASP.NET Core 2.0 implementation

### ISSUE THREAD

**Issue by EricSpeidel** [Sustainsys/Saml2#815]
In order to register my SP with my IDP, I have to supply them with Metadata describing my SP. 
This used to be available at ~/AuthServices, and should now be available at ~/Saml2 as @AndersAbel mentioned. However, accessing this will throw the following exception:

`System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Incorrect Content-Type: 
  Source=Microsoft.AspNetCore.Http
  StackTrace:
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Form()
   at Sustainsys.Saml2.AspNetCore2.HttpRequestExtensions.ToHttpRequestData(HttpContext httpContext, Func 2 cookieDecryptor) in C:\Users\EricSpeidel\source\repos\Saml2-master (3)\Saml2-master\Sustainsys.Saml2.AspNetCore2\HttpRequestExtensions.cs:line 28
   at Sustainsys.Saml2.AspNetCore2.Saml2Handler.HandleRequestAsync() in C:\Users\EricSpeidel\source\repos\Saml2-master (3)\Saml2-master\Sustainsys.Saml2.AspNetCore2\Saml2Handler.cs:line 109
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()`
**How to reproduce:**
Build the latest version and run the .NET Core sample application. Accessing https://localhost:44342/Saml2 will throw the exception.

**Comment by EricSpeidel** [comment]
Tested with Chrome and Edge. Same outcome.

**Comment by gauravthakur25** [comment]
Hi,

Is this issue fixed? I am still not able to get metadata from ~/Saml2. If there's any other url to get metadata, kindly let me know.

Regards,
Gaurav

**Comment by AndersAbel** [comment]
@gauravthakur25 What version are you running?

**Comment by gauravthakur25** [comment]
Sustainsys.Saml2.AspNetCore2 2.0.0--preview01
I need to make it work for ASP.NET core

**Comment by gauravthakur25** [comment]
Thanks @AndersAbel will drop you a mail.
