### ISSUE TITLE
 ID4149: The Saml2SecurityToken is rejected because the SAML2:Assertion specifies a OneTimeUse condition. Enforcement of the OneTimeUse condition is not supported by default. 

### ISSUE THREAD

**Issue by swathibaggam** [Sustainsys/Saml2#826]
Getting below error when trying to login  to IDP . 
Please let us know whether we can set OneTimeUse  in Kentor configuration?
Please let us know how to fix this issue

**System.IdentityModel.Tokens.SecurityTokenValidationException: ID4149: The Saml2SecurityToken is rejected because the SAML2:Assertion specifies a OneTimeUse condition. Enforcement of the OneTimeUse condition is not supported by default. To customize the enforcement of Saml2Conditions, extend Saml2SecurityTokenHandler and override ValidateConditions.**
   at System.IdentityModel.Tokens.Saml2SecurityTokenHandler.ValidateConditions(Saml2Conditions conditions, Boolean enforceAudienceRestriction)
   at Kentor.AuthServices.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Kentor.AuthServices.Saml2P.Saml2Response.GetClaims(IOptions options)
   at Kentor.AuthServices.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState)
   at Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Kentor.AuthServices.HttpModule.Saml2AuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Please find below kentor configuration details 
`<kentor.authServices entityId="https://SP/AuthServices" returnUrl="https://SP/" >
    <identityProviders>
      <add entityId="IDP" signOnUrl="https://IDP/GetAccess/Saml/IDP/SSO/Unsolicited?GA_SAML_SP=https://SP/AuthServices" allowUnsolicitedAuthnResponse="true" binding="HttpRedirect" metadataLocation="~/App_Data/IDP.metadata.xml" loadMetadata = "true" >
        <signingCertificate fileName="~/App_Data/IDP.cer" />
      </add>
    </identityProviders>
    <federations>      
    </federations>
    <serviceCertificates>
      <add fileName="~/App_Data/Kentor.AuthServices.Tests.pfx" />
    </serviceCertificates>
    </kentor.authServices>`
Is this issue related to below pull request?
#524(Handle OneTimeUse SAML2Reponse)

**Comment by AndersAbel** [comment]
Yes, it's related to that PR. Until that is merged, this won't work.
