### ISSUE TITLE
Sequence contains more than one element when there is two descriptor present in the idp metadata

### ISSUE THREAD

**Issue by robertpmansion** [Sustainsys/Saml2#923]
I'm getting this error whenever there are idps in a federated metadata that contains two descriptor: `IDPSSODescriptor` and  `AttributeAuthorityDescriptor` as an example shown below.

```
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:shibmd="urn:mace:shibboleth:metadata:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" entityID="https://test.edu.au/idp/shibboleth" xsi:schemaLocation="urn:oasis:names:tc:SAML:2.0:metadata saml-schema-metadata-2.0.xsd urn:mace:shibboleth:metadata:1.0 shibboleth-metadata-1.0.xsd http://www.w3.org/2000/09/xmldsig# xmldsig-core-schema.xsd">
   <IDPSSODescriptor protocolSupportEnumeration="urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol">
      <Extensions>
         <shibmd:Scope regexp="false">test.edu.au</shibmd:Scope>
      </Extensions>
      <KeyDescriptor use="signing">...</KeyDescriptor>
      <ContactPerson contactType="technical">
         <Company>Test University</Company>
         <GivenName>Peter</GivenName>
         <SurName>Pan</SurName>
         <EmailAddress>peter.pan@test.edu.au</EmailAddress>
      </ContactPerson>
      <ArtifactResolutionService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://test-idp.test.edu.au:8443/idp/profile/SAML2/SOAP/ArtifactResolution" index="1" isDefault="false"/>
      <ArtifactResolutionService Binding="urn:oasis:names:tc:SAML:1.0:bindings:SOAP-binding" Location="https://test-idp.test.edu.au:8443/idp/profile/SAML1/SOAP/ArtifactResolution" index="2" isDefault="false"/>
      <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://test-idp.test.edu.au/idp/profile/SAML2/Redirect/SLO"/>
      <NameIDFormat>
         urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
      </NameIDFormat>
      <NameIDFormat>
         urn:oasis:names:tc:SAML:2.0:nameid-format:transient
      </NameIDFormat>
      <NameIDFormat>urn:mace:shibboleth:1.0:nameIdentifier</NameIDFormat>
      <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://test-idp.test.edu.au/idp/profile/SAML2/Redirect/SSO"/>
      <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="https://test-idp.test.edu.au/idp/profile/SAML2/POST-SimpleSign/SSO"/>
      <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://test-idp.test.edu.au/idp/profile/SAML2/POST/SSO"/>
      <SingleSignOnService Binding="urn:mace:shibboleth:1.0:profiles:AuthnRequest" Location="https://test-idp.test.edu.au/idp/profile/Shibboleth/SSO"/>
   </IDPSSODescriptor>
   <AttributeAuthorityDescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol">
      <Extensions>
         <shibmd:Scope regexp="false">test.edu.au</shibmd:Scope>
      </Extensions>
      <KeyDescriptor use="signing">...</KeyDescriptor>
      <ContactPerson contactType="technical">...</ContactPerson>
      <AttributeService Binding="urn:oasis:names:tc:SAML:1.0:bindings:SOAP-binding" Location="https://test-idp.test.edu.au:8443/idp/profile/SAML1/SOAP/AttributeQuery"/>
      <AttributeService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://test-idp.test.edu.au:8443/idp/profile/SAML2/SOAP/AttributeQuery"/>
      <NameIDFormat>
         urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
      </NameIDFormat>
      <NameIDFormat>
         urn:oasis:names:tc:SAML:2.0:nameid-format:transient
      </NameIDFormat>
      <NameIDFormat>urn:mace:shibboleth:1.0:nameIdentifier</NameIDFormat>
   </AttributeAuthorityDescriptor>
   <Organization>
      <OrganizationName xml:lang="en">test.edu.au</OrganizationName>
      <OrganizationDisplayName xml:lang="en">Test University</OrganizationDisplayName>
      <OrganizationURL xml:lang="en">http://helpdesk.test.edu.au</OrganizationURL>
   </Organization>
</EntityDescriptor>
```
I have check further into the codes and saw that we only take single descriptor which cause the issue.

```
private void ReadMetadataIdpDescriptor(ExtendedEntityDescriptor metadata)
{
	var idpDescriptor = metadata.RoleDescriptors
		.OfType<IdentityProviderSingleSignOnDescriptor>().Single();
		
	// ....
}
```

Should this type of metadata be supported because currently as the code shown above only get single descriptor?

**Comment by AndersAbel** [comment]
That can't be the error, the `OfType<IdentityProviderSingleSignOnDescriptor>()` call filters out only the IdpSsoDescriptor.

Please post the stack trace of the exception.

**Comment by vv-dev-team** [comment]
@AndersAbel here is the stack trace.

 ```
  at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Sustainsys.Saml2.IdentityProvider.ReadMetadataIdpDescriptor(ExtendedEntityDescriptor metadata) in C:\Users\Robert.Mansion\Documents\VertigoVentures\Projects\Saml2\Sustainsys.Saml2\IdentityProvider.cs:line 416
   at Sustainsys.Saml2.IdentityProvider.ReadMetadata(ExtendedEntityDescriptor metadata) in C:\Users\Robert.Mansion\Documents\VertigoVentures\Projects\Saml2\Sustainsys.Saml2\IdentityProvider.cs:line 408
   at Sustainsys.Saml2.Federation.LoadMetadata() in C:\Users\Robert.Mansion\Documents\VertigoVentures\Projects\Saml2\Sustainsys.Saml2\Federation.cs:line 156
```

**Comment by AndersAbel** [comment]
Thanks, any chance you could put that sample, failing metadata into a unit test and run it, to get something that's debuggable? Or I'll look at it when I have time (which is not anytime soon I'm afraid, unless you want to discuss commercial options to allow me to prioritize this)

**Comment by robertpmansion** [comment]
@AndersAbel here is the stack trace.

 at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
  at Sustainsys.Saml2.IdentityProvider.ReadMetadataIdpDescriptor(ExtendedEntityDescriptor metadata) in C:\Users\Robert.Mansion\Documents\Org\Projects\Saml2\Sustainsys.Saml2\IdentityProvider.cs:line 416
  at Sustainsys.Saml2.IdentityProvider.ReadMetadata(ExtendedEntityDescriptor metadata) in C:\Users\Robert.Mansion\Documents\Org\Projects\Saml2\Sustainsys.Saml2\IdentityProvider.cs:line 408
  at Sustainsys.Saml2.Federation.LoadMetadata() in C:\Users\Robert.Mansion\Documents\Org\Projects\Saml2\Sustainsys.Saml2\Federation.cs:line 156

**Comment by vv-dev-team** [comment]
@AndersAbel I'll be working on the metadata. However, you could also refer to this: 'https://md.test.aaf.edu.au/aaf-test-metadata.xml'. I believe this is publicly available. There are failing IDPs in that federated metadata.

**Comment by robertpmansion** [comment]
@AndersAbel I'll be working on the metadata. However, you could also refer to this: 'https://md.test.aaf.edu.au/aaf-test-metadata.xml'. I believe this is publicly available. There are failing IDPs in that federated metadata.

**Comment by robertpmansion** [comment]
@AndersAbel I have found what causing the issue it is because some of the `entityID` defined as `urn` instead of 'https//...' which the tool was not able to load the metadata. However, the current behaviour is it goes to the catch with the exception and remove all of the previously added IDPs from the federation. Should we just ignore those IDPs without the URL location?

**Comment by robertpmansion** [comment]
@AndersAbel I have found the issue. This is because there is a duplicate IDPSSODescriptor in the EntityDescriptor of one of the Idps. I think since it is a test federated metadata they did remove the duplicate. However should we cover this in the tool if something like this happen like changing the `Single()` to `First()` to prevent this happening?

**Comment by robertpmansion** [comment]
@AndersAbel the organisation that manage the federated metadata has corrected their metadata to remove the Descriptor with two IDSSODescriptors however should we handle this on the codes like changing the `Single()` to `First()`?

**Comment by AndersAbel** [comment]
I don't like the idea of just picking the first item in case there are multiple options, what if the second is the one we really want to use?

I went to have a look at the metadata spec to see what it says about multiple role descriptors (such as `<IDPSSODescriptor>` of the same type:

> It is RECOMMENDED that if multiple role descriptor elements of the same type appear, that they do not share overlapping protocolSupportEnumeration values. Selecting from among multiple role descriptor elements of the same type that do share a protocolSupportEnumeration value is undefined within this specification, but MAY be defined by metadata profiles, possibly through the use of other distinguishing extension attributes.

So following that principle we should filter out anything that doesn't contain `urn:oasis:names:tc:SAML:2.0:protocol`, and expect that there only is one descriptor with that value. But looking at your metadata example that would mean filtering out both nodes...

So I don't know the best way forward, do you have any ideas?
