### ISSUE TITLE
Logout relaystate issue

### ISSUE THREAD

**Issue by LukeeK** [Sustainsys/Saml2#938]
Hi,
we are developing web app (SP) which has to authenticate users against F5 (idp) with usage of Sustain/Kentor. They can  login without problem, but we are having issue with logout.
 Kentor fails to process logout responses that are coming back from F5 to our application (~/AuthServices/Logout). From the stack of the error  && logout url  we assume that problem is in relaystate param being duplicate in url. Unfortuantelly we do not have access to F5 but it seems that logout endpoint has "Redirect" binding setted.

Anyway do You think it is this valid scenario regarding SAML and its spec  and Kentor should handle it or it is some Idp (f5) problem ??

Url:  .../AuthServices/Logout?SAMLResponse=7P1HjiRJ0rz/X8Vh+wg3N/OosDCEeyJRiQIciNpERMWiNglzN/UIQ7qbeZqaBeL4ifCISETGIm5gsI3ADPo8EL3A8uXUd8kRPBpnC5JNKUnANk4buy/Iv+2fiSAv5RJV37FBrtzexbAGHJxFSE59Z1Fe3goSvZVOoUFpVQ8oQyM3r39Xkk2pHLwLrnEdSaq3grxTxpSGWcMX0Oa6rme1yLhgbc6ZbrSmrGE1BZLsbl7s7FUhRqgsBmVDQRjNxITyCePbjMmcyzz7T5LKrq92W1cQo9Uc+K952y5mguZ8IQRTjNdzNs9B1FmuSPIGGIxVYeQcQhhQpumH8iGoaWvs3hs9bU36GsNhA/5oGsD00gO59CJHL3/XxvMuFCL4M46UN5yK4XAPOw9JjR5SRLcc0xXyvYlNUCHiQ/ztNCQ71UV4boDjb7mGzwgYwJO0XKYPg2/558rLrwAAAP//&RelayState=SqH5_tce7tYF22ALxWQVX8hK_xERAsma_sL5PcF36bz-UIadA5sLRxJc&SigAlg=http://www.w3.org/2000/09/xmldsig#rsa-sha1&Signature=o2/sS1W6C+797Wm2sJGSORHdszGGa1GV/LCgpCqqZ7EWdGKP4ZQqQEBe0K7vUAgSf4KLK1npmgYAn76U6RntMNNERZ8efancYj/dcb8Dk1WvkukDAXHzks9Dy0iDmwJhpVBSYwZFHYPDglMXsjw/wmb72TZ7jVJ/IvGrUlL1LcxJL0WQZ0/P7H8BufenxtNTnAAkxNyjTOkNPTsrZwrbV73J5ubXnMgg1bK1uNbcsb8YAlDoJl3NDwjRqbO4AA+kpnTHSl3nVtBm2nEZBSyST8ezKOj0XGhLNQ8HrlHpeFBQS13yhizFx29W3RZkWwTKJQAtjiINZdB7kBdAZmLziA==&RelayState=SqH5_tce7tYF22ALxWQVX8hK_xERAsma_sL5PcF36bz-UIadA5sLRxJc 

Exception information: 
    Exception type: InvalidOperationException 
    Exception message: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Kentor.AuthServices.WebSso.HttpRequestData.Init(String httpMethod, Uri url, String applicationPath, IEnumerable`1 formData, IEnumerable`1 cookies, Func`2 cookieDecryptor, ClaimsPrincipal user)
   at Kentor.AuthServices.Owin.OwinContextExtensions.<ToHttpRequestData>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kentor.AuthServices.Owin.KentorAuthServicesAuthenticationHandler.<InvokeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---....

 Unfortunatelly we do not have access to F5 setup &

**Comment by AndersAbel** [comment]
The F5 shouldn't generate duplicate RelayState, I think the library is doing the right thing and blocking this.
