### ISSUE TITLE
What to set for Saml2ClaimTypes.LogoutNameIdentifier value

### ISSUE THREAD

**Issue by jallenstein** [Sustainsys/Saml2#977]
I have a custom Identity model and am having to generate my `ClaimsIdentity` object from scratch. I'm getting an error when calling the logout endpoint:

`System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Sustainsys.Saml2.ClaimsExtensions.ProcessLogoutNameIdentifier(Claim claim)
   at Sustainsys.Saml2.IdentityProvider.CreateLogoutRequest(ClaimsPrincipal user)
   at Sustainsys.Saml2.WebSso.LogoutCommand.InitiateLogout(HttpRequestData request, Uri returnUrl, IOptions options, Boolean terminateLocalSession)
   at Sustainsys.Saml2.WebSso.LogoutCommand.Run(HttpRequestData request, String returnPath, IOptions options)
   at Sustainsys.Saml2.Owin.Saml2AuthenticationHandler.<InvokeAsync>d__4.MoveNext()`

After some digging I see that you're running a split on the value of `Saml2ClaimTypes.LogoutNameIdentifier`. I'm storing my value as such:

`claimsIdentity.AddClaim(new Claim(Saml2ClaimTypes.LogoutNameIdentifier, "{entityId}", ClaimValueTypes.String, "{entityId}"));`
Where "{entityId}" is the same value in my web.config for my idp and is a url. If I switch the value to be anything else, my logging shows my entity is not found and logout is never attempted. What should that value be?

**Comment by AndersAbel** [comment]
@jallenstein The logoutnameidentifier format is not specified and is subject to change. You should carry over the logoutnameidentifier that was generated by the library in the login sequence.

But if you really want to see how it is created, read the source.
